### PR TITLE
Add xfs support

### PR DESCRIPTION
**Pull request by sylviacy**
Since xfs is used as a standard file system on RHEL / CentOS 7 and later, xfs should be supported by Warewulf.

### CODE REVIEW

**Comment by jmstover** [comment]
There was an error on RHEL 8.

```
linux.c:23:10: fatal error: sys/ustat.h: No such file or directory
```

From the xfsprogs build if I'm reading the details right.

We'd also need to get a sign-off from the maintainer of xfsprogs that providing the binary is fine and doesn't make warewulf a derivitave work of XFS by providing the tools.

As far as this goes... I'm morally against XFS existing after needing to spend days restoring a filesystem that had a bunch of 0 size files after a power outage (xfs_db hell IIRC, and lots of `dd` and offsets to rebuild files from where they existed on the filesystem).

**Comment by sylviacy** [comment]
> There was an error on RHEL 8.
> 
> ```
> linux.c:23:10: fatal error: sys/ustat.h: No such file or directory
> ```
> 
> From the xfsprogs build if I'm reading the details right.
> 
> We'd also need to get a sign-off from the maintainer of xfsprogs that providing the binary is fine and doesn't make warewulf a derivitave work of XFS by providing the tools.
> 
> As far as this goes... I'm morally against XFS existing after needing to spend days restoring a filesystem that had a bunch of 0 size files after a power outage (xfs_db hell IIRC, and lots of `dd` and offsets to rebuild files from where they existed on the filesystem).

Can you provide your email address and warewulf or openhpc mail list？
So I can cc xfsprogs maintainer and warewulf members to discuss whether we can support xfs filesystem.

**Comment by jmstover** [comment]
I'm on the Open HPC list. For warewulf it's warewulf@lbl.gov

**Comment by jmstover** [comment]
@sylviacy I didn't realize exactly how old the 4.5.0 version of xfsprogs was. I'd probably try at least 5.1.0 ... That was released after RHEL 8 was released. 

https://mirrors.edge.kernel.org/pub/linux/utils/fs/xfs/xfsprogs/

**Comment by sandeen** [comment]
We had this discussion on the list, but I figured I'd chime in here too.

I am the current xfsprogs maintainer.  I am not a lawyer, and I do not hold copyright on all (or even most) code in xfsprogs.  I have no authority to "sign off" or otherwise comment on what is or is not an acceptable use of the xfsprogs package; that is all spelled out in the GPL license it is distributed with.

If you have any questions about whether your redistribution is within the terms of the license, you will need to consult a legal/licensing expert, not me.  I am in no way an arbiter of acceptable GPL code use.  This is why I have not agreed to add my name to this statement; it's not my place to reinterpret or clarify the terms of the GPL.

Thanks,
-Eric

**Comment by bensallen** [comment]
Thanks @sandeen for taking the time to respond here and discuss on the mailing list.

**Pull request closed without merging**
