### PR TITLE
Update openEuler-22.03 templates with the latest improvements from OpenHPC 3.0

### PR DESCRIPTION
**Pull request by martin-g**
During the testing of the OpenHPC 3.0 release the following improvements have been made to the openEuler templates:

- https://github.com/openhpc/ohpc/commit/4947268940f6fecef9129447e66262740f622c20
- https://github.com/openhpc/ohpc/commit/02355c5682f4e30d4b471e63422b4cc1e4ecf143
- https://github.com/openhpc/ohpc/commit/0daafb80ec09d52fc40d8292c3661c0aa5104ff8

### CODE REVIEW

**Review by Yikun — APPROVED** [review]
LGTM

**Comment by Yikun** [comment]
@bensallen Would you mind taking a look? This PR passed the E2E test of OpenHPC Warewulf. [1]

image

[1] http://test.openhpc.community:8080/job/3.x/

**Comment by Yikun** [comment]
@bensallen Would you mind taking a look?

**Comment by bensallen** [comment]
Thanks @martin-g and @Yikun

**Pull request merged**
